# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp wrapper for adsamp algorithm
#'
#' @param n number of variates to draw
#' @param log_dens log density function, a function with a single parameter
#' @param initialPoints at least 2 points in support to seed algorithm
#' @param minRange lower bound of support
#' @param maxRange upper bound of support
#'
raw_ad_sample <- function(n, log_dens, initialPoints, minRange, maxRange) {
    .Call('_adsample_raw_ad_sample', PACKAGE = 'adsample', n, log_dens, initialPoints, minRange, maxRange)
}

#' Duplicate wrapper for adsamp algorithm for debugging. This version
#' returns the algorithm state as well as the variates.
#'
#' @param n number of variates to draw
#' @param log_dens log density function, a function with a single parameter
#' @param initialPoints at least 2 points in support to seed algorithm
#' @param minRange lower bound of support
#' @param maxRange upper bound of support
#' @param maxiter maximum number of iterations; zero if no limit
#'
raw_ad_sample_debug <- function(n, log_dens, initialPoints, minRange, maxRange, maxiter) {
    .Call('_adsample_raw_ad_sample_debug', PACKAGE = 'adsample', n, log_dens, initialPoints, minRange, maxRange, maxiter)
}

